plugins: 
 - jekyll-feed
 - jekyll-sitemap
 - jekyll-seo-tag

github: [metadata]

collections:
  authors:
    output: true

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
      layout: "default"
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "publications"
    values:
      layout: "publication"
  - scope:
      path: ""
      type: "conferences"
    values:
      layout: "conference"

#theme: clean-jekyll-theme 
